<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit60f086770d5349e6691208457d739ed2
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PayBridge\Plaid\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PayBridge\Plaid\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit60f086770d5349e6691208457d739ed2', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PayBridge\Plaid\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit60f086770d5349e6691208457d739ed2', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PayBridge\Plaid\Vendor\Composer\Autoload\ComposerStaticInit60f086770d5349e6691208457d739ed2::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
