<?php

// autoload_static.php @generated by Composer

namespace PayBridge\Plaid\Vendor\Composer\Autoload;

class ComposerStaticInit60f086770d5349e6691208457d739ed2
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\' => 36,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\' =>
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'PayBridge\\Plaid\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/BeforeValidException.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\CachedKeySet' => __DIR__ . '/..' . '/firebase/php-jwt/src/CachedKeySet.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/src/ExpiredException.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\JWK' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWK.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\JWT' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWT.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\JWTExceptionWithPayloadInterface' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\Key' => __DIR__ . '/..' . '/firebase/php-jwt/src/Key.php',
        'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/SignatureInvalidException.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit60f086770d5349e6691208457d739ed2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit60f086770d5349e6691208457d739ed2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit60f086770d5349e6691208457d739ed2::$classMap;

        }, null, ClassLoader::class);
    }
}
