<?php

// autoload_static.php @generated by Composer

namespace Buckmerce\Plaid\Vendor\Composer\Autoload;

class ComposerStaticInit85c106048dd220db9be6802288641395
{
    public static $prefixLengthsPsr4 = array (
        'B' =>
        array (
            'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\' => 36,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\' =>
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\BeforeValidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/BeforeValidException.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\CachedKeySet' => __DIR__ . '/..' . '/firebase/php-jwt/src/CachedKeySet.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\ExpiredException' => __DIR__ . '/..' . '/firebase/php-jwt/src/ExpiredException.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\JWK' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWK.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\JWT' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWT.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\JWTExceptionWithPayloadInterface' => __DIR__ . '/..' . '/firebase/php-jwt/src/JWTExceptionWithPayloadInterface.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\Key' => __DIR__ . '/..' . '/firebase/php-jwt/src/Key.php',
        'Buckmerce\\Plaid\\Vendor\\Firebase\\JWT\\SignatureInvalidException' => __DIR__ . '/..' . '/firebase/php-jwt/src/SignatureInvalidException.php',
        'Buckmerce\\Plaid\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit85c106048dd220db9be6802288641395::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit85c106048dd220db9be6802288641395::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit85c106048dd220db9be6802288641395::$classMap;

        }, null, ClassLoader::class);
    }
}
