<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PayBridge\\Plaid\\Vendor\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
);
