<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit85c106048dd220db9be6802288641395
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Buckmerce\Plaid\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Buckmerce\Plaid\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit85c106048dd220db9be6802288641395', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Buckmerce\Plaid\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit85c106048dd220db9be6802288641395', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Buckmerce\Plaid\Vendor\Composer\Autoload\ComposerStaticInit85c106048dd220db9be6802288641395::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
