<?php

declare(strict_types=1);

namespace Buckmerce\Plaid\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Where the front-end files and translations live. assets/ is generated by `npm run build`,
 * ignored by Git and shipped only in the release ZIP, and it is flat: every stylesheet, script
 * and image sits directly in assets/. Translations are tracked and shipped in languages/.
 *
 * A path the runtime code asks for that the build does not produce, a build target that writes
 * into a subdirectory, or a release that would leave a referenced file out fails here, on a
 * checkout that has never been built.
 */
final class AssetPathsTest extends TestCase
{
    private const FLAT_ASSET = '~^assets/[a-z0-9]+(?:-[a-z0-9]+)*\.(css|js|svg|png|jpg|webp)$~';

    private static function root(): string
    {
        return dirname(__DIR__, 2);
    }

    private static function read(string $relative): string
    {
        $content = file_get_contents(self::root() . '/' . $relative);
        self::assertIsString($content, $relative . ' is readable.');
        return $content;
    }

    /** @return list<string> Runtime PHP files, relative to the plugin directory. */
    private static function runtime_files(): array
    {
        $files = array('buckmerce-plaid.php', 'uninstall.php');
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator(self::root() . '/src', \FilesystemIterator::SKIP_DOTS));
        foreach ($iterator as $file) {
            if ($file instanceof \SplFileInfo && 'php' === $file->getExtension()) {
                $files[] = substr($file->getPathname(), strlen(self::root()) + 1);
            }
        }
        sort($files);
        return $files;
    }

    /** @return array<string, list<string>> Asset path => runtime files that reference it. */
    private static function referenced_assets(): array
    {
        $references = array();
        foreach (self::runtime_files() as $relative) {
            $source = self::read($relative);
            preg_match_all('~([\'"])(assets/[^\'"]*)\1~', $source, $literals);
            // Every mention of assets/ is one complete, literal file path: nothing is assembled at runtime.
            self::assertSame(substr_count($source, 'assets/'), count($literals[2]), $relative . ' builds an asset path dynamically.');
            foreach ($literals[2] as $asset) {
                $references[$asset][] = $relative;
            }
        }
        ksort($references);
        return $references;
    }

    /** @return list<string> */
    private static function manifest_list(string $name): array
    {
        preg_match('/^' . preg_quote($name, '/') . '=\((.*?)^\)/ms', self::read('scripts/lib/package-manifest.sh'), $block);
        preg_match_all('/^\s+(?:\'([^\']+)\'|([A-Za-z0-9._\/-]+))/m', $block[1] ?? '', $entries, PREG_SET_ORDER);
        return array_map(static fn (array $entry): string => '' !== $entry[1] ? $entry[1] : $entry[2], $entries);
    }

    public function test_runtime_code_references_only_files_the_build_puts_directly_in_assets(): void
    {
        $references = self::referenced_assets();
        self::assertNotEmpty($references);
        foreach ($references as $asset => $files) {
            $where = $asset . ' (' . implode(', ', array_unique($files)) . ')';
            self::assertMatchesRegularExpression(self::FLAT_ASSET, $asset, 'assets/ has no subdirectories: ' . $where);
            $name = pathinfo($asset, PATHINFO_FILENAME);
            $source = match (pathinfo($asset, PATHINFO_EXTENSION)) {
                'css' => 'resources/scss/' . $name . '.scss',
                'js' => 'resources/ts/' . $name . '.ts',
                default => 'resources/images/' . basename($asset),
            };
            self::assertFileExists(self::root() . '/' . $source, 'No front-end source builds ' . $where);
        }
        // What the code loads is exactly what a release must contain.
        $required = array_values(array_filter(self::manifest_list('bmfp_release_required'), static fn (string $path): bool => str_starts_with($path, 'assets/')));
        sort($required);
        self::assertSame(array_keys($references), $required, 'The release manifest requires exactly the assets the runtime code loads.');
    }

    public function test_every_build_target_writes_directly_into_assets(): void
    {
        $package = json_decode(self::read('package.json'), true);
        self::assertIsArray($package);
        $built = array();
        foreach ($package['targets'] as $name => $target) {
            self::assertSame('assets', $target['distDir'], 'Target ' . $name . ' must write directly into assets/.');
            self::assertFalse($target['sourceMap'], 'Target ' . $name . ' must not emit a source map.');
            self::assertFileExists(self::root() . '/' . $target['source'], 'Target ' . $name . ' has a source file.');
            $extension = str_ends_with($target['source'], '.scss') ? 'css' : 'js';
            $output = 'assets/' . pathinfo($target['source'], PATHINFO_FILENAME) . '.' . $extension;
            self::assertSame($output, $package[$name] ?? null, 'package.json names the output file of target ' . $name . '.');
            self::assertMatchesRegularExpression(self::FLAT_ASSET, $output);
            $built[] = $output;
        }
        foreach (glob(self::root() . '/resources/images/*') ?: array() as $image) {
            $built[] = 'assets/' . basename($image);
        }
        sort($built);
        self::assertSame(array_keys(self::referenced_assets()), $built, 'Everything the build produces is loaded, and everything loaded is built.');
        self::assertStringContainsString('DEST_DIR="$BASE_DIR/assets"', self::read('scripts/copy-images.sh'), 'Images are copied directly into assets/.');
        self::assertSame('rm -rf assets .parcel-cache', $package['scripts']['clean'], 'A build starts from an empty assets/ directory.');
        foreach (array_filter($built, static fn (string $path): bool => str_ends_with($path, '.js')) as $script) {
            self::assertStringContainsString('node --check ' . $script, $package['scripts']['lint'], 'The compiled ' . $script . ' is syntax-checked.');
        }
    }

    public function test_assets_are_generated_ignored_by_git_and_packaged_flat(): void
    {
        $ignored = array_map('trim', explode("\n", self::read('.gitignore')));
        self::assertContains('/assets/', $ignored, 'assets/ is build output and never committed.');
        self::assertNotContains('/languages/', $ignored, 'Translations are tracked.');
        self::assertContains('assets', self::manifest_list('bmfp_release_top_level'), 'The release ZIP contains assets/.');
        self::assertContains('languages', self::manifest_list('bmfp_release_top_level'), 'The release ZIP contains languages/.');
        $patterns = array_values(array_filter(self::manifest_list('bmfp_release_allowlist'), static fn (string $pattern): bool => str_starts_with($pattern, '^assets')));
        self::assertNotEmpty($patterns);
        foreach ($patterns as $pattern) {
            self::assertSame(1, substr_count($pattern, '/'), 'The release allowlist accepts no subdirectory of assets/: ' . $pattern);
        }
        self::assertStringContainsString("fail 'assets/ must not contain subdirectories'", self::read('scripts/verify-package.sh'));
        self::assertStringContainsString("fail 'assets/ must be ignored by Git'", self::read('scripts/audit-source.sh'));
        self::assertStringContainsString("fail 'assets/ contains tracked build output'", self::read('scripts/audit-source.sh'));
    }

    public function test_bundled_translations_are_registered_while_the_plugin_loads(): void
    {
        $main = self::read('buckmerce-plaid.php');
        self::assertStringContainsString(" * Domain Path: /languages\n", $main, 'WordPress 6.8+ registers languages/ from this header.');
        // WordPress 6.6 and 6.7 need the explicit registration, as a top-level statement: inside an
        // `init` callback it runs too late when another plugin lists the payment gateways earlier.
        self::assertMatchesRegularExpression(
            '/^if \( isset\( \$GLOBALS\[\'wp_textdomain_registry\'\] \) [^\n]+\{\n\t\$GLOBALS\[\'wp_textdomain_registry\'\]->set_custom_path\( \'buckmerce-plaid\', BUCKMERCE_PLAID_DIR \. \'languages\' \);\n\}$/m',
            $main
        );
        self::assertStringNotContainsString('load_plugin_textdomain', $main, 'Registering the directory is enough: WordPress loads translations on first use.');
        foreach (self::runtime_files() as $relative) {
            self::assertStringNotContainsString('wp_set_script_translations', self::read($relative), $relative . ': scripts receive translated text from PHP.');
        }
        $catalogues = glob(self::root() . '/languages/buckmerce-plaid-*.po') ?: array();
        self::assertNotEmpty($catalogues);
        foreach ($catalogues as $catalogue) {
            foreach (array('.mo', '.l10n.php') as $compiled) {
                self::assertFileExists(substr($catalogue, 0, -3) . $compiled, basename($catalogue) . ' is compiled.');
            }
        }
    }
}
